version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/django_deployment


hooks:
  BeforeInstall:
    - location: scripts/beforeinstall.sh
      timeout: 300
      runas: root

  Install:
    - location: scripts/install.sh
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: scripts/afterinstall.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: scripts/applicationstart.sh
      timeout: 300
      runas: ubuntu
