version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/django_deployment
permissions:
  - object: /home/ubuntu/django_deployment
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  ApplicationStop:
    - location: scripts/applicationstop.sh
      timeout: 180
      runas: ubuntu

  BeforeInstall:
    - location: scripts/beforeinstall.sh
      timeout: 300
      runas: root

  Install:
    - location: scripts/install.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/afterinstall.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: scripts/applicationstart.sh
      timeout: 300
      runas: ubuntu
