

services:
  web:
    build: .
    command: gunicorn todo_project.wsgi:application --bind 0.0.0.0:8000 
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env

volumes:
  postgres_data: 
