#!/bin/bash
#cd /home/ubuntu/django_deployment || exit
#echo "[AfterInstall] Pulling Docker images..."
#docker-compose pull
#!/bin/bash
echo "[AfterInstall] Pulling the Docker image..."

cd /home/ubuntu/django_deployment || exit 1

# Load IMAGE_TAG generated by CodeBuild
export IMAGE_TAG=$(cat image_tag.txt)

# Pull the specific Docker image with the tag from Docker Hub
docker pull vishnu9/todo-app:$IMAGE_TAG
